package com.example.pet_coctails.fragments.randomCocktail

data class CocktailRandomData(
    val imageLink: String,
    val cocktailName: String,
    val id: String,
    val category: String,
    val cocktailType: String,
    val glassType: String,
    val instructions: String,
    val ingredient1: String,
    val ingredient2: String,
    val ingredient3: String,
    val ingredient4: String,
    val ingredient5: String,
    val ingredient6: String,
    val ingredient7: String,
    val ingredient8: String,
    val ingredient9: String,
    val ingredient10: String,
    val ingredient11: String,
    val ingredient12: String,
    val ingredient13: String,
    val ingredient14: String,
    val ingredient15: String,
    val measureIngredient1: String,
    val measureIngredient2: String,
    val measureIngredient3: String,
    val measureIngredient4: String,
    val measureIngredient5: String,
    val measureIngredient6: String,
    val measureIngredient7: String,
    val measureIngredient8: String,
    val measureIngredient9: String,
    val measureIngredient10: String,
    val measureIngredient11: String,
    val measureIngredient12: String,
    val measureIngredient13: String,
    val measureIngredient14: String,
    val measureIngredient15: String

)
